Support for multiple zabbix servers and individual port setting for each server.
shamil/puppet-zabbix-reports pull request #5
Opened 2016-11-16 14:34 UTC by erikoest

Please review. And thanks for your suggestions. Ruby is really not my native tongue, so feel free to rewrite and improve.

2016-11-16 16:01 UTC, shamil requested changes
Generally looks good. Couple of changes and we are ready to merge it. 

I can merge it now, and do the changes myself.

Also, please squash your commits, to have single commit for this PR

2016-11-16 16:01 UTC, shamil commented on lib/puppet/reports/zabbix.rb
> +        Puppet.error "zabbix send failed - #{result['info']}" if result['response'] != 'success'
no need for `if result['response'] != 'success'`, the `if` above already does it

2016-11-16 16:01 UTC, shamil commented on zabbix.yaml
> +:zabbix_host:
This should be `:zabbix_hosts`, keep old `:zabbix_host` unchanged, and just merge it to the zabbix_host array inside the login

2016-11-16 16:01 UTC, shamil commented on lib/puppet/util/zabbix_sender.rb
> -end
This file should not contain any changes, please reset it

2016-11-18 12:15 UTC, erikoest commented
On 11/16/2016 05:01 PM, Alex Simenduev wrote:
> *@shamil* requested changes on this pull request.
> 
> Generally looks good. Couple of changes and we are ready to merge it.
> 
> I can merge it now, and do the changes myself.

Thanks.

> Also, please squash your commits, to have single commit for this PR

I don't think it is recommended to squash commits which have already
been pushed (and possibly shared with others). Wouldn't it be better if
you merge it and squash the commits before you push the change on your
repo?

/ Erik


> 
> ------------------------------------------------------------------------
> 
> In lib/puppet/reports/zabbix.rb
> <https://github.com/shamil/puppet-zabbix-reports/pull/5#pullrequestreview-8842559>:
> 
>>  
> -    # send metrics to zabbix
> -    Puppet.debug "sending zabbix report for host #{self.host}, at #{zabbix_sender.serv}:#{zabbix_sender.port}"
> -    result = zabbix_sender.send! host_overrides.fetch(self.host, self.host)
> +      # send metrics to zabbix
> +      Puppet.debug "sending zabbix report for host #{self.host}, at #{zabbix_sender.serv}:#{zabbix_sender.port}"
> +      result = zabbix_sender.send! host_overrides.fetch(self.host, self.host)
> +
> +      # validate the response. if it fails, keep on sending to all
> +      # zabbix servers before reporting the error.
> +      if result['response'] != 'success'
> +        Puppet.error "zabbix send failed - #{result['info']}" if result['response'] != 'success'
> 
> no need for |if result['response'] != 'success'|, the |if| above already
> does it
> 
> ------------------------------------------------------------------------
> 
> In zabbix.yaml
> <https://github.com/shamil/puppet-zabbix-reports/pull/5#pullrequestreview-8842559>:
> 
>> @@ -1,6 +1,11 @@
>  ---
> -:zabbix_host: zabbix.domain.tld
> -:zabbix_port: 10051
> +:zabbix_host:
> 
> This should be |:zabbix_hosts|, keep old |:zabbix_host| unchanged, and
> just merge it to the zabbix_host array inside the login
> 
> ------------------------------------------------------------------------
> 
> In lib/puppet/util/zabbix_sender.rb
> <https://github.com/shamil/puppet-zabbix-reports/pull/5#pullrequestreview-8842559>:
> 
>> @@ -64,4 +64,4 @@ def rawdata(data)
>      end
>  
>    end
> -end
> 
> This file should not contain any changes, please reset it
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/shamil/puppet-zabbix-reports/pull/5#pullrequestreview-8842559>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AELFwAd2UPnWcuDqh4kO6USUIZb-36d-ks5q-yjdgaJpZM4Kz72k>.
>

2016-11-18 16:29 UTC, shamil commented
Alright, I've squashed your commits into single one and applied some other changes.
Closing this PR. Thanks for contribution!

2016-11-18 16:29 UTC, closed without merging